### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by fourstepper** [peektwice/gvm-ansible#5]
Hi, just wanted to say thanks for this. I hope this will stay supported throughout future versions and I will make sure to hop in to be of help if I find something problematic, at least in the form of a bug report

Have a great day!

**Comment by peektwice** [comment]
I'll do my best. If newer versions come out, and you'd like to see an update here, let me know. I do this in my spare time, so it's sort of a best effort. But you're also welcome to fork and make pull requests with your own submissions. Thanks and have a great day yourself.
